CREATE TABLE AFFIRM_PAYMENT_GROUP 
(
	PAYMENT_GROUP_ID VARCHAR2(40 BYTE) NOT NULL ENABLE, 
	CHECKOUT_TOKEN 	VARCHAR2(254 BYTE), 
	CHARGE_ID 	VARCHAR2(254 BYTE),
	CONSTRAINT AFFIRM_PAY_GROUP_PK PRIMARY KEY (PAYMENT_GROUP_ID) ENABLE, 
	CONSTRAINT AFFIRM_PAY_GROUP_DCSPP_PG_FK1 FOREIGN KEY (PAYMENT_GROUP_ID) REFERENCES DCSPP_PAY_GROUP (PAYMENT_GROUP_ID) ENABLE
);

alter table AFFIRM_PAYMENT_GROUP add AUTH_TXN_ID varchar2 (254 byte);
